version: '3'

tasks:
  test:
    desc: Run all Go tests (including spec)
    cmds:
      - go test ./... -v

  test-spec:
    desc: Run only the spec tests
    cmds:
      - go test -v ./spec -run Test_Spec

