name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Describe the problem you're trying to solve or the use case for this feature.
      placeholder: I'm trying to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also considered...

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What part of the project does this feature relate to?
      options:
        - Parser (lexer, parser, token)
        - Library API (Recipe, Ingredient, etc.)
        - Renderers (Cooklang, Markdown, HTML)
        - Unit Conversion
        - CLI Tool
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: spec
    attributes:
      label: Cooklang Specification
      description: Does this relate to the Cooklang specification?
      options:
        - label: This feature is part of the official Cooklang specification
        - label: This feature extends beyond the Cooklang specification
        - label: I'm not sure

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used.
      placeholder: |
        Example recipe syntax:
        ```
        @new-feature{value}
        ```
        
        Example Go code:
        ```go
        recipe.NewMethod()
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
