name: Security Vulnerability
description: Report a security vulnerability (please be discreet)
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important Security Notice
        
        **If this is a critical security vulnerability, please consider using [GitHub's private vulnerability reporting](../../security/advisories/new) instead of this public issue form.**
        
        When reporting security issues publicly:
        - Do NOT include exploit code or detailed reproduction steps
        - Do NOT include sensitive data or credentials
        - Keep the description general until we can establish secure communication

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity
      description: How severe do you estimate this vulnerability to be?
      options:
        - Critical - Remote code execution, data breach
        - High - Significant security impact
        - Medium - Limited security impact
        - Low - Minor security concern
        - Unknown - I'm not sure
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      options:
        - Input validation / Injection
        - Denial of Service
        - Information disclosure
        - Dependency vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: General Description
      description: |
        Provide a general description of the vulnerability WITHOUT including:
        - Detailed reproduction steps
        - Exploit code
        - Sensitive data
      placeholder: |
        Describe the general nature of the vulnerability...
        
        Example: "The parser does not properly validate X when processing Y"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: "v0.4.0 and earlier"
    validations:
      required: true

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Acknowledgment
      description: Please confirm the following
      options:
        - label: I have not included detailed exploit information in this public issue
          required: true
        - label: I understand the maintainers may contact me for more details privately
          required: true
        - label: I will not publicly disclose additional details until a fix is released
          required: true

  - type: textarea
    id: contact
    attributes:
      label: Secure Contact Method (Optional)
      description: |
        If you'd like us to contact you securely for more details, provide a contact method.
        Consider using a method that supports encryption (e.g., email with PGP).
      placeholder: "You can reach me at..."
